"""Candidate-aware direct image observations; no complete legal-text review."""

# Each tuple is page, region, visible wording, exact native anchor (if useful),
# source-only conclusion, uncertainty, and optional date value/role.
NOTES = {
    "el-paso-planning-fees-sd011": {
        "issuer": "El Paso County, Planning and Community Development",
        "kind": "county_department", "role": "planning_and_community_development_fee_schedule",
        "title": "El Paso County 2026 Planning and Community Development Fee Schedule",
        "observations": [(1, "top banner", "2026 Planning and Community Development\nFee Schedule- Effective Date May 1, 2026", None,
            "County-branded planning/development fee schedule; effective date is printed in its banner.",
            "First-page native text is empty; no full fee-row, footnote or applicability review.",
            "2026-05-01", "source_stated_effective")],
        "qualifications": ["The actual visible effective date is May 1, 2026; the 2026 filename alone is not its evidence.", "Five source pages retained; only physical page 1 viewed for issuer/title/date, not all fee associations."],
    },
    "el-paso-boh-ehs-fees-sd011": {
        "issuer": "El Paso County Board of Health / El Paso County Public Health",
        "kind": "county_board_of_health", "role": "board_of_health_fee_schedule_and_civil_penalties",
        "title": "El Paso County Board of Health, Chapter 3: Fee Schedule and Civil Penalties (English)",
        "observations": [(1, "cover and footer", "REGULATIONS OF THE EL PASO COUNTY BOARD OF HEALTH\nChapter 3\nFee Schedule and Civil Penalties\nApproved by the Board of Health October 25, 2023", "Approved by the Board of Health October 25, 2023",
            "Board of Health fee/civil-penalty chapter, not county commissioner legislation.",
            "Approval is a document statement, not independent authentication of board action.", "2023-10-25", "source_stated_approval"),
            (2, "section 3.1 opening", "Effective January 1, 2024, the following fees are adopted by the Board of Health", "Effective January 1, 2024, the following fees are adopted by the Board of Health",
            "The first fee page expressly gives a 2024 effective-date statement.",
            "No entire five-page fee table or later amendment reconciliation; filename June 2025 is not an adoption date.", "2024-01-01", "source_stated_effective")],
        "qualifications": ["English and Spanish PDFs are distinct received artifacts; translation equivalence is not reviewed.", "The viewed fee table includes air quality, body art, child care and OWTS categories; it is not exclusively an OWTS schedule."],
    },
    "el-paso-ordinance-26-01-sd011": {
        "issuer": "Board of County Commissioners of El Paso County, Colorado",
        "kind": "county_board_of_commissioners", "role": "stormwater_management_ordinance",
        "title": "El Paso County Ordinance 26-01: Stormwater Management Program Required by the MS4 Permit",
        "observations": [(1, "heading and recitals", "COUNTY ORDINANCE NO. 26-01\nORDINANCE TO DEVELOP, IMPLEMENT, AND ENFORCE THE STORMWATER MANAGEMENT PROGRAM REQUIRED BY THE MUNICIPAL SEPARATE STORM SEWER SYSTEM PERMIT", "STORMWATER",
            "The ordinance concerns the county stormwater/MS4 program; municipal in MS4 is not City of Colorado Springs ownership.",
            "Native extraction contains OCR errors; this is title/role review only, not all 23 pages or execution verification.", None, None),
            (1, "upper recorder stamp", "04/08/2026 08:46:34 AM\n226032306", None,
            "Visible recorder stamp states April 8, 2026; the native OCR starts with an incorrect month.",
            "Recording is not adoption or effectiveness; no signature identity or currentness is certified.", "2026-04-08", "recording_stamp")],
        "qualifications": ["Do not describe Ordinance 26-01 as a land-use or wildfire ordinance solely from its catalog position.", "Stamp OCR is visibly unreliable; source bytes and uncorrected native text remain unchanged."],
    },
    "el-paso-ldc-wildfire-appendix-e-sd011": {
        "issuer": "El Paso County Planning and Community Development publication context",
        "kind": "county_department", "role": "land_development_code_wildfire_appendix",
        "title": "El Paso County LDC Appendix E: Wildfire Resiliency Requirements",
        "observations": [(1, "title and E.1.2", "APPENDIX E – WILDFIRE RESILIENCY REQUIREMENTS\nThe provisions of this Appendix E apply to all areas of unincorporated El Paso County that lie within the Wildland-Urban Interface but outside the boundaries of any Fire District.", "The provisions of this Appendix E apply to all areas of unincorporated El \nPaso County that lie within the Wildland-Urban Interface but outside the \nboundaries of any Fire District.",
            "First page explicitly limits stated territory to the unincorporated WUI outside fire-district boundaries.",
            "No adoption/effective date is visible on this page; the separate adopting instrument and applicability maps were not reconciled.", None, None)],
        "qualifications": ["County posting plus the document's territorial wording support a county appendix role; this does not establish adoption or current application.", "Eighteen pages are preserved, not all provisions or exceptions checked."],
    },
    "el-paso-open-burning-22-001-sd011": {
        "issuer": "Board of County Commissioners of the County of El Paso, State of Colorado",
        "kind": "county_board_of_commissioners", "role": "open_burning_ordinance",
        "title": "El Paso County Ordinance 22-001: Regulation of Open Burning in Unincorporated Areas",
        "observations": [(1, "title and recitals", "ORDINANCE NO. 22-001\nORDINANCE FOR THE REGULATION OF OPEN BURNING IN THE UNINCORPORATED AREAS OF EL PASO COUNTY", "ORDINANCE FOR THE REGULATION OF OPEN BURNING",
            "County open-burning ordinance; the first-page recitals also discuss conditional firework restrictions.",
            "The applicable annual/stage restriction resolutions were not reviewed. No present fire ban or operative restriction follows.", None, None),
            (1, "upper recorder stamp", "07/13/2022 09:42:54 AM\n222094518", "07/13/2022 09:42:54 AM",
            "This is the recorder-stamp date, separately from legal adoption/effect.",
            "Top stamp name is partly cropped; no identity authentication.", "2022-07-13", "recording_stamp")],
        "qualifications": ["Exact source hash matches inherited manifest claims; historical original bytes were not opened.", "Current restrictions cannot be inferred from the ordinance alone."],
    },
    "el-paso-ldc-chapter-1-sd011": {
        "issuer": "El Paso County, Colorado", "kind": "county_department",
        "role": "land_development_code_chapter_1", "title": "El Paso County Land Development Code, Chapter 1: Introductory Provisions",
        "observations": [(1, "heading, section 1.3 and footer", "Chapter One\nINTRODUCTORY PROVISIONS\nEffective 01/09/2018", "Effective 01/09/2018",
            "First page identifies county LDC and states that it does not apply within incorporated municipalities.",
            "Only this front page is directly viewed among 72 pages. The 2016 URL filename is not the visible effective-date statement.", "2018-01-09", "source_stated_effective")],
        "qualifications": ["Exact inherited URL and historical digest match, but no fresh source-page anchor was preserved.", "This is a chapter artifact, not proof of a complete LDC or reconciliation with later amendments."],
    },
    "el-paso-ldc-chapter-2-sd011": {
        "issuer": "El Paso County, Colorado", "kind": "county_department",
        "role": "land_development_code_chapter_2", "title": "El Paso County Land Development Code, Chapter 2: Administration",
        "observations": [(1, "heading and footer", "Chapter Two\nADMINISTRATION\nEffective 12/12/2017", "Effective 12/12/2017",
            "County LDC administration chapter; first page separately describes a Procedures Manual.",
            "This PDF is not that separate Procedures Manual. Later amendments and all seven pages were not reviewed.", "2017-12-12", "source_stated_effective")],
        "qualifications": ["Inherited URL/no fresh preserved anchor; recorded digest equality does not prove current law.", "The filename's 2016 label differs from the viewed effective-date statement."],
    },
    "el-paso-ldc-chapter-5-sd011": {
        "issuer": "El Paso County, Colorado", "kind": "county_department",
        "role": "land_development_code_chapter_5", "title": "El Paso County Land Development Code, Chapter 5: Use and Dimensional Standards",
        "observations": [(1, "heading and footer", "Chapter Five\nUSE AND DIMENSIONAL STANDARDS\nEffective 01/09/2018", "Effective 01/09/2018",
            "County use/dimensional standards chapter, including a first-page introduction to use tables.",
            "Only page 1 of 172 viewed; tables, zone columns and all later pages have not been certified. Repeated visible 5.2.3 labels remain uncorrected.", "2018-01-09", "source_stated_effective")],
        "qualifications": ["Inherited URL/no fresh preserved anchor; source hash matches inherited claims.", "A large chapter is not full county zoning coverage or a current consolidated code."],
    },
    "el-paso-unsafe-buildings-18-03-sd011": {
        "issuer": "Board of County Commissioners, County of El Paso, State of Colorado",
        "kind": "county_board_of_commissioners", "role": "adopting_resolution_with_unsafe_buildings_ordinance",
        "title": "El Paso County Resolution 17-321 with Ordinance 18-03: Removal of Unsafe Buildings",
        "observations": [(1, "heading and adoption paragraph", "RESOLUTION NO. 17-321\nRESOLUTION ADOPTING ORDINANCE NO. 18-03, REQUIRING THE REMOVAL OF UNSAFE BUILDINGS", "RESOLUTION NO. 17-321",
            "The PDF begins with a resolution, rather than only the ordinance named in its filename.",
            "Source's 2017 resolution/18-03 designation is preserved, not editorially corrected.", None, None),
            (2, "execution line and signature region", "DONE THIS 21st day of November, 2017, at Colorado Springs, Colorado.", "November 2017",
            "Day/month fields appear handwritten; signature and seal marks are present beside printed office labels.",
            "No signature identity or execution authentication. This is a source-stated execution date.", "2017-11-21", "source_stated_execution"),
            (3, "ordinance title and section 3", "ORDINANCE NO. 18-03\nREQUIRING THE REMOVAL OF UNSAFE BUILDINGS", "REQUIRING THE REMOVAL OF UNSAFE BUILDINGS",
            "The actual ordinance starts on physical page 3; section 3 states unincorporated coverage and a conditional municipal opt-in/IGA route.",
            "No municipality is established as opted in by this document review; only three of eight pages inspected.", None, None)],
        "qualifications": ["Preserve resolution and appended ordinance together in their original eight-page artifact.", "No full repeal chain, final effectiveness or municipality opt-in confirmation."],
    },
    "el-paso-school-district-fees-sd011": {
        "issuer": "Not explicitly identified on the one-page school-district fee sheet",
        "kind": "unresolved_school_fee_issuer", "role": "school_district_development_fee_comparison_sheet",
        "title": "School District Fees for Development in El Paso County (issuer unresolved)",
        "observations": [(1, "full one-page sheet", "SCHOOL DISTRICT FEES for DEVELOPMENT IN EL PASO COUNTY\nSCHOOL DISTRICT #\nFEE per SINGLE FAMILY UNIT/PATIO HOMES\nFEE for ALL OTHER RESIDENTIAL TYPES per DWELLING UNIT", None,
            "Rows name districts 3, 20, 38, 49 and All Other Districts; sheet compares two residential fee categories.",
            "No issuer, authorizing instrument or date is visible. County hosting does not establish the levy/collection authority; 2010 in the filename is not a source-stated effective date.", None, None)],
        "qualifications": ["Excluded from proposed county intake pending explicit issuer/layer decision; do not automatically assign a district or county.", "The native text is empty; this is issuer/role review, not a complete checked fee-table dataset."],
    },
    "el-paso-boh-admin-regulations-sd011": {
        "issuer": "El Paso County Board of Health / El Paso County Public Health",
        "kind": "county_board_of_health", "role": "board_of_health_administrative_regulations",
        "title": "El Paso County Board of Health, Chapter 2: Administrative Regulations",
        "observations": [(1, "cover and lower-left date", "REGULATIONS OF THE EL PASO COUNTY BOARD OF HEALTH\nChapter 2\nAdministrative Regulations\n5/23/2012", "5/23/2012",
            "Explicit Board of Health/Public Health identification supports a separate health-board role within county intake.",
            "The date has no adoption/effective label on the cover; do not replace it with 2011 or June 2025 filename labels.", "2012-05-23", "unlabeled_cover_date")],
        "qualifications": ["No full administrative-regulations or subsequent-amendment review.", "Board of Health is not silently relabeled Board of County Commissioners."],
    },
    "el-paso-boh-bylaws-sd011": {
        "issuer": "El Paso County Board of Health / El Paso County Public Health",
        "kind": "county_board_of_health", "role": "board_of_health_bylaws",
        "title": "El Paso County Board of Health, Chapter 1: Bylaws (English)",
        "observations": [(1, "cover and lower-left date", "Chapter 1\nBylaws\nEl Paso County Board of Health\n5/23/2012", "5/23/2012",
            "Board of Health bylaws chapter, distinct from commissioner legislation.",
            "Cover date is unlabeled; the 2011/June 2025 filename is not a legal date.", "2012-05-23", "unlabeled_cover_date")],
        "qualifications": ["English and Spanish bylaws remain separate files, with no translation-equivalence claim.", "Only cover inspected; entire governance text/current board status remains unreviewed."],
    },
    "el-paso-boh-bylaws-spanish-sd011": {
        "issuer": "Junta de Salud del Condado de El Paso / El Paso County Public Health",
        "kind": "county_board_of_health", "role": "board_of_health_bylaws_spanish_text",
        "title": "El Paso County Board of Health, Capítulo 1: Estatutos (Spanish)",
        "observations": [(1, "cover", "REGLAMENTO DEL PASO\nJUNTA DE SALUD DEL CONDADO\nCONDADO DE EL PASO, COLORADO\nCapítulo 1\nEstatutos", "Capítulo 1",
            "Spanish-language bylaws artifact explicitly identifies the El Paso County Board of Health.",
            "The unusual visible REGLAMENTO DEL PASO wording is not silently corrected. No cover date is visible or borrowed from English.", None, None)],
        "qualifications": ["Distinct six-page Spanish artifact; English has five pages. Page counts do not establish translation equivalence.", "No date/currentness inferred from the URL or English companion."],
    },
    "el-paso-boh-ehs-fees-spanish-sd011": {
        "issuer": "Junta de Salud del Condado de El Paso / Salud Publica del Condado de El Paso",
        "kind": "county_board_of_health", "role": "board_of_health_fee_schedule_and_civil_penalties_spanish_text",
        "title": "El Paso County Board of Health, Capítulo 3: Lista de tarifas y sanciones civiles (Spanish)",
        "observations": [(1, "cover and clipped footer", "Capítulo 3\nLista de tarifas y sanciones civiles\nAprobado por la Junta de Salud el 25 de octubre", "Capítulo 3",
            "Spanish Board of Health fee/civil-penalty chapter; approval-footer continuation is clipped in the rendered source.",
            "Native extraction contains hidden/clipped year text. Do not certify its visible year or import the English approval date.", None, None),
            (2, "section 3.1 opening", "A partir del 1 de enero de 2024, la Junta de Salud adopta las siguientes tarifas", "1 de enero de 2024",
            "The top of page 2 visibly states a January 1, 2024 commencement date.",
            "Only two of six pages viewed; no entire table or English/Spanish equivalence review. Footer still clips approval continuation.", "2024-01-01", "source_stated_effective")],
        "qualifications": ["Distinct Spanish file with a visibly clipped approval footer, preserved unchanged.", "Do not treat embedded text beyond the visible page as an image-confirmed year."],
    },
    "el-paso-hosted-cgs-review-guide-sd011": {
        "issuer": "Colorado Geological Survey",
        "kind": "colorado_geological_survey", "role": "external_agency_land_use_review_referral_and_fee_guide",
        "title": "Colorado Geological Survey Land Use Review Referral and Fee Guide (county-hosted copy)",
        "observations": [(1, "branding, title and opening", "COLORADO GEOLOGICAL SURVEY\nLAND USE REVIEW REFERRAL AND FEE GUIDE\nInformation for project applicants and their representatives", "The Colorado Geological Survey (CGS) is an external review agency for counties, municipalities, and \nschool districts throughout Colorado.",
            "The guide names CGS as an external review agency for counties, municipalities and school districts; it is not an El Paso County fee instrument.",
            "CGS institutional/authority registry placement requires an explicit decision; county asset hosting alone does not supply ownership.", None, None),
            (2, "FAQ, contact and footer", "CGS serves as an independent technical reviewer and advisor to local governments\nColoGeoSurvey Land Use Review Referral and Fee Guide - June 18, 2026", "ColoGeoSurvey Land Use Review Referral and Fee Guide - June 18, 2026",
            "The second page describes CGS's advisory role and shows a June 18, 2026 footer date and a mines.edu contact address.",
            "Footer date is a document label, not verified adoption/effectiveness. Links and email were not opened or contacted.", "2026-06-18", "document_footer_date")],
        "qualifications": ["Excluded from county intake pending explicit issuer/layer decision; no automatic state-layer assignment is made.", "Both pages viewed for role/date; no full numeric fee-table certification or application advice."],
    },
}
