"""Assemble a bounded, candidate-aware audit without editing received evidence."""
from pathlib import Path
from datetime import datetime, timezone
from hashlib import sha256
import json, shutil
from audit_models import Audit
B=Path(__file__).parent
A='received/20260911T190213Z/'
BASE=Path('/Users/mcoors/Documents/Project Geode')
def ref(rel):
    p=B/rel
    return dict(path=rel,sha256=sha256(p.read_bytes()).hexdigest(),size_bytes=p.stat().st_size)
pre=B.parent/'pre-review-2026-09-11'
for name in ('SOURCE_PRECHECK.md','SOURCE_PRECHECK.json','SOURCE_PRECHECK.schema.json'):
    p=B/'comparison-evidence/root-precheck'/name;p.parent.mkdir(parents=True,exist_ok=True)
    if not p.exists():shutil.copyfile(pre/name,p);p.chmod(0o444)
    assert sha256(p.read_bytes()).digest()==sha256((pre/name).read_bytes()).digest()

sources=[dict(priority_id='SD009-01',authority_id='CO-COUNTY-LARIMER',file=ref(A+'raw/july13_attachment_5519.pdf'),pages=2,inspected_physical_pages=[1,2],claimed_requested_url='https://larimercoco.portal.civicclerk.com/event/8139/files/attachment/5519',claimed_final_url='https://larimercoco.portal.civicclerk.com/event/8139/files/attachment/5519',provenance_class='received_pdf_download_claim_not_http_verified',exact_delivered_bytes_verified=True,exact_publisher_original_verified=False,acquisition_time=None,role='staff_recommendation',metadata_notes=['PDF title: Extension of Data Center Moratorium; producer Aspose.PDF for .NET 22.12.0; creation 2026-06-30 and modification 2026-07-06 are file metadata, not independently established publication, adoption or download dates.','The browser notes call this a downloaded PDF, but retained publisher response headers and final download URL metadata are absent. The Mac request to the same URL instead retained a 1,289-byte HTML shell.'],visible_source_findings=['Both full pages inspected. Hearing label July 13, 2026; staff recommends extension until February 25, 2027 and supplies a suggested motion. This does not enact the recommendation.','Page 1 reports January 27, 2026 administrative approval and a February 9 extension until August 25, 2026. These are statements in a later staff memorandum.','Page 2 references Attachment A, but this two-page file does not contain that attachment.'],legal_currentness='not_verified'),
 dict(priority_id='SD009-02',authority_id='CO-COUNTY-LARIMER',file=ref(A+'raw/july13_addendum_5539.pdf'),pages=5,inspected_physical_pages=[1,2,3,4,5],claimed_requested_url='https://larimercoco.portal.civicclerk.com/event/8139/files/attachment/5539',claimed_final_url='https://larimercoco.portal.civicclerk.com/event/8139/files/attachment/5539',provenance_class='browser_print_derivative',exact_delivered_bytes_verified=True,exact_publisher_original_verified=False,acquisition_time=None,role='unsigned_extension_draft',metadata_notes=['The browser-session summary explicitly says the item download control did not yield a separate browser file and this was saved as a native browser PDF print of the rendered document.','PDF title: Land Use Hearing • Agendas & Minutes • CivicClerk; Chrome/151.0.0.0 creator, Skia/PDF m151 producer, creation/modification D:20260911190715+00\'00\'. The metadata is consistent with browser printing, not a publisher-original PDF or verified retrieval timestamp.','The session summary identifies the event page as requested and attachment 5539 as final; consolidated B003 uses the attachment for both fields. These are event/navigation claims, not a captured HTTP redirect chain.'],visible_source_findings=['All five full pages inspected. Page 1 labels this a Published Addendum incorporated more than 24 hours before the scheduled July 13 hearing; no exact publication timestamp appears in that statement.','Page 2 labels Attachment A as a resolution to Establish; page 3 body title says EXTEND. Preserve the cover/body difference.','Page 3 recital literally says April 7, 2026 and Reception No. 20260016505. It does not say January 27 or 20260005307.','Page 4 proposes six months through and included February 25, 2027, or earlier qualifying code adoption, unless renewed or amended separately; territorial scope is all unincorporated Larimer County. These are unsigned draft terms.','Page 5 literally prints effective as of August 25, 2025, then expiry February 25, 2027 unless earlier terminated or further extended. DATED, Chair and ATTEST/Deputy County Clerk lines are blank. The printed 2025 must not be silently corrected to 2026.'],legal_currentness='not_verified'),
 dict(priority_id='SD009-03',authority_id='CO-COUNTY-LARIMER',file=ref(A+'raw/feb09_minutes.pdf'),pages=20,inspected_physical_pages=[1,9,10],claimed_requested_url='https://larimercoco.portal.civicclerk.com/event/2812/files/agenda/3563',claimed_final_url='https://larimercoco.portal.civicclerk.com/event/2812/files/agenda/3563',provenance_class='received_pdf_download_claim_not_http_verified',exact_delivered_bytes_verified=True,exact_publisher_original_verified=False,acquisition_time=None,role='board_minutes',metadata_notes=['PDF metadata title: CMR - Minutes - 2-9-2026 - ADMINISTRATIVE MATTERS.pdf; producer Microsoft: Print To PDF; creation/modification D:20260217143113-07\'00\'. These do not establish certification, publication or retrieval.','The first visible page says Land Use Hearing. The metadata filename and printed heading are separate evidence fields.','Both SD007-B012 and SD009-B005 claim the exact agenda/3563 URL, but the former binds a 194-page agenda packet hash 15933b2b… and the latter this 20-page minutes hash 88e4c7dc…. No retained HTTP headers or actual download-link export resolves that conflict.'],visible_source_findings=['Only full physical pages 1, 9 and 10 were directly inspected; the other 17 pages were structurally parsed, not visually certified or transcribed.','Page 1 labels minutes of Monday, February 9, 2026 and a Land Use Hearing beginning 3:00 p.m.','Page 9 contains staff recommendation and discussion. Page 10 records Commissioner Stephens moving approval of the resolution to extend the temporary moratorium until August 25, 2026; Motion carried 3-0.','The motion precedes the 5:30 p.m. recess and the next Land Use Hearing at 6:30 p.m. It must not be attributed to the later hearing. A minutes vote is evidence of recorded Board action, not the absent signed resolution.'],legal_currentness='not_verified')]

F=[]
def finding(status,title,detail,*paths):
    F.append(dict(id=f'ATLAS-SD009-{len(F)+1:02}',disposition=status,title=title,detail=detail,evidence_paths=list(paths)))
finding('accept','Immutable delivery custody passes','97 original files (71,496,968 bytes) were copied first and rehashed; no symlinks. All six advertised hashes, 51 inventory entries, five top-level aliases and 33 nested aliases match. Main tar has 54 matching safe file members and all 51 inventoried files. Browser tar has 33 matching files and omits 18 inventory entries that are present in the main package/loose delivery. Archive copies are not additional source captures.','CUSTODY_RECEIPT.json','structural-facts.json')
finding('correct','12 rows do not prove 12 public attempts','The consolidated log has 12 public rows and one local reread, with nine distinct targets: eight HTTPS URLs and one search pseudo-URI. B003 folds a spinner failure and one retry into one public row, establishing at least 13 public attempts. The underlying browser list also separates navigate/download actions that cannot be mapped to exact additional HTTP requests from this package. The known lower bound is within 30 events/20 targets, but complete cap compliance and exact count cannot be certified.',A+'logs/attempted_urls.json',A+'logs/browser_attempts.json')
finding('qualify','Browser acquisition remains reconstructed','Browser clocks are unknown; no successful PDF response headers, redirect chain or saved download-link attributes accompany the notes. Do not promote browser_200_pdf/browser_200_pdf_minutes to observed HTTP status. Five Mac HTTP200 bodies are identical SPA shells, and the hub body is HTTP403; those headers do not authenticate the separately retained browser PDFs. No denied access was retried during this audit.',A+'logs/attempted_urls.json',A+'exports/browser_session_summary.json',A+'logs/SD009-E001.headers.txt',A+'logs/SD009-E006.headers.txt')
finding('correct','Attachment 5539 is a browser-print derivative','The frozen PDF is valid received evidence, but its byte hash binds a rendered browser print, not an exact publisher-original PDF. The summary explicitly discloses this and Chrome/Skia metadata is consistent. Keep this classification with every later use; the downloaded-original claim for the other two PDFs is likewise not independently HTTP-verified.',A+'exports/browser_session_summary.json',A+'raw/july13_addendum_5539.pdf')
finding('correct','Same exact claimed URL binds different artifacts','SD007-B012 and SD009-B005 both claim https://larimercoco.portal.civicclerk.com/event/2812/files/agenda/3563. SD007 retained a 194-page packet (15933b2b…); SD009 retained a 20-page minutes document (88e4c7dc…). This is stronger than same path family. Treat the minutes URL as an unresolved acquisition association; do not infer a genuine source replacement, legal update or stable direct download endpoint.',A+'logs/attempted_urls.json','comparison-evidence/sd007/logs/attempted_urls.json','comparison-facts.json')
finding('correct','Printed 2025 is clear, not OCR uncertainty','The priority JSON draft_effective_as_of_ocr value suggests 2026 with uncertainty. Direct inspection of addendum physical page 5 shows August 25, 2025 clearly. Preserve 2025 as a literal draft date and flag its inconsistency without repairing the source. Expiry February 25, 2027 is conditional on no earlier termination/further extension; execution fields are blank.',A+'priority_candidates_final.json','page-evidence/july13_addendum_5539-p05.png')
finding('qualify','Draft recital and title differences remain unresolved','Addendum physical page 3 cites April 7, 2026 / Reception No. 20260016505, whereas prior recorded January material and the staff memo use a different origin date. No retained final instrument reconciles these. Page 2 says Establish and the body title says EXTEND. Neither the retrospective recital nor the July hearing language certifies adoption of this unsigned draft.','page-evidence/july13_addendum_5539-p02.png','page-evidence/july13_addendum_5539-p03.png','page-evidence/july13_addendum_5539-p05.png')
finding('accept','Staff recommendation and minutes action are distinct','The two-page July staff memo recommends February 25, 2027 and has a suggested motion; Attachment A is referenced but not included in that file. February minutes page 10 records an August 25, 2026 extension motion carried 3-0. This is useful evidence of recorded Board action, with no separate executed February resolution provided. Only minutes pages 1, 9 and 10 were visually reviewed.','page-evidence/july13_attachment_5519-p02.png','page-evidence/feb09_minutes-p10.png')
finding('qualify','Negative search and nonposting claims have limited support','S001 preserves a December 19 fee-search query but no search response/result list; its clock equals report assembly. No separate 2008 CPI search event/result is retained. The July file list is a narrative array, not a preserved rendered DOM or complete catalog response. Unlocated in this package does not establish that an executed instrument or later minutes do not exist.',A+'logs/attempted_urls.json',A+'exports/browser_session_summary.json',A+'report-20260911T191427Z.md')
finding('correct','Eight priorities are not eight resources','IDs SD009-01 through SD009-08 are unique and all retain CO-COUNTY-LARIMER / pending_intake / not_verified. Only 01–03 bind new PDF artifacts; 04 references an existing SD007 packet; 05–08 are gap placeholders, and 07 combines a fee-adopting instrument and Attachment A schedule. Keep resource and gap counts separate.',A+'priority_candidates_final.json')
finding('correct','Backlog strings are missing targets, not discovered URLs','All four backlog url fields contain descriptive labels, not URLs. Normalize them as unlocated targets with URL null, preserving the original file. Staff memo page 1 also visibly supplies three exact YouTube links for January 27, February 9 and June 29 meetings, absent from the backlog; these are unopened video leads, not this audit\'s sources or proof of the final executed instruments.',A+'logs/backlog.json','page-evidence/july13_attachment_5519-p01.png')
finding('accept','Exact pinned and current comparisons do not imply current law','All four exported blobs were hash/size checked and independently matched git cat-file at exact commit 0bc3658f6c7c9f378a5083884714dc4111677afd. Full 48,390-row historical manifest and 12-row manual manifest have no direct/linked target URL or incoming hash matches; source registry and county coverage have no exact target URL matches. Current 48,390/38-row manifests likewise have no three incoming hashes, but current manual row 34 matches the old SD007 packet. Among 542 ordinary files under current _RAW_ARCHIVE, no incoming PDF even shares a size, so none shares its bytes. These are custody/deduplication facts, not proof of new law or original acquisition.','comparison-facts.json')

def ex(s,p,region,text,qualification,image):
    return dict(source_priority_id=s,physical_page=p,region=region,wording=text,qualification=qualification,image=ref('page-evidence/'+image))
excerpts=[
 ex('SD009-01',2,'Suggested Motion','I move that the Board of County Commissioners approve the resolution to extend the temporary moratorium on data center facilities until February 25, 2027.','Staff-proposed motion, not a vote or adopted instrument. Line wrapping is normalized.','july13_attachment_5519-p02.png'),
 ex('SD009-02',3,'First recital identifiers','April 7, 2026; Reception No. 20260016505','Two exact identifiers from the first recital, presented as selected excerpts with a separator; not a continuous full-sentence transcription. The recital remains unreconciled.','july13_addendum_5539-p03.png'),
 ex('SD009-02',4,'Last paragraph','This moratorium, as extended, is effective in all of unincorporated Larimer County.','Literal unsigned-draft territorial statement; not a certification of present scope or enforceability.','july13_addendum_5539-p04.png'),
 ex('SD009-02',5,'Effective/expiry paragraph','This resolution shall be effective as of August 25, 2025, and shall expire on February 25, 2027, unless earlier terminated or further extended pursuant to statute.','Literal 2025 retained; line wrapping normalized. Draft with blank DATED, Chair and attestation fields.','july13_addendum_5539-p05.png'),
 ex('SD009-03',10,'Motion immediately before 5:30 p.m. recess','Commissioner Stephens moved that the Board of County Commissioners approve the resolution to extend the temporary moratorium on data center facilities until August 25, 2026.\n\nMotion carried 3-0.','Directly inspected minutes text, with line wrapping normalized. No independent certification of minutes or exact download endpoint; not the separate executed resolution.','feb09_minutes-p10.png')]

support=['CUSTODY_RECEIPT.json','CUSTODY_RECEIPT.schema.json','structural-facts.json','comparison-facts.json']
support += [str(p.relative_to(B)) for p in sorted((B/'comparison-evidence').rglob('*')) if p.is_file()]
data=dict(schema_version=1,assignment='geode-source-discovery-009',reviewed_at=datetime.now(timezone.utc).isoformat(),reviewer='Atlas / Codex independent intake audit',review_mode='candidate_aware_direct_page_and_custody_review',disposition='accept_custody_with_provenance_and_claim_corrections',legal_currentness='not_verified',production_changes=False,network_requests=0,comparison_commit='0bc3658f6c7c9f378a5083884714dc4111677afd',custody=dict(files=97,bytes=71496968,symlinks=0,advertised_hashes_checked=6,top_level_aliases_checked=5,nested_aliases_checked=33,inventory_files=51,inventory_bytes=19290536,main_tar_files=54,main_tar_missing_inventory_files=0,browser_tar_files=33,browser_tar_missing_inventory_files=18,all_originals_unchanged=True),acquisition=dict(consolidated_rows=13,reported_public_events=12,local_reread_events=1,distinct_public_targets=9,distinct_https_urls=8,distinct_search_queries=1,minimum_public_attempts_supported=13,exact_public_event_count=None,exact_event_completeness_verified=False,max_public_events=30,max_distinct_targets=20,cap_breach_demonstrated=False,cap_compliance_certified=False,browser_http_status_verified=False,browser_acquisition_times_verified=False),priority_records=8,new_pdf_artifacts=3,prior_resource_references=1,gap_placeholders=4,total_structural_pdf_pages=27,directly_inspected_full_pages=10,full_minutes_transcription_certified=False,supporting_files=[ref(p) for p in support],sources=sources,findings=F,excerpts=excerpts,unresolved_gaps=['Exact publisher acquisition URL, HTTP status and original-byte provenance for the retained minutes; resolve the exact agenda/3563 association conflict.','Publisher-original bytes for attachment 5539; current artifact is a browser print.','Executed/signed/recorded February 9 extension instrument, independently bound to the recorded minutes motion.','July final minutes or vote and final executed/recorded extension instrument; reconcile literal 2025 and April 7/20260016505 recital before any currentness conclusion.','December 19, 2023 fee-adopting instrument and Attachment A schedule; equity-reduction resolution remains a separate instrument.','Numbered 2008 CPI authorization resolution and scope; search completeness is not demonstrated.'])
audit=Audit.model_validate_json(json.dumps(data))
(B/'INTAKE_AUDIT.json').write_text(audit.model_dump_json(indent=2)+'\n')
(B/'INTAKE_AUDIT.schema.json').write_text(json.dumps(Audit.model_json_schema(),indent=2)+'\n')
md=['---','title: Atlas Sherlock009 custody and acquisition audit','assignment_id: geode-source-discovery-009','review_mode: candidate_aware_direct_page_and_custody_review','status: accept_custody_with_provenance_and_claim_corrections','legal_currentness: not_verified','reviewed_at: '+audit.reviewed_at.isoformat(),'production_changes: false','network_requests: 0','---','','# Disposition','','Accept the frozen delivery as received evidence with the corrections below. It contains three new PDF artifacts (27 structural pages), not eight newly collected resources. Exact publisher acquisition is unverified; attachment 5539 is explicitly a browser-print derivative. No record is promoted to legally current, adopted, certified, or complete.','','The review consulted the frozen candidate package and root source precheck. It is not blind. I directly inspected all two staff-memo pages, all five rendered-addendum pages, and minutes physical pages 1, 9 and 10: ten full pages. The other 17 minutes pages were structurally checked, not visually certified.','','# Custody and scope','','97 unchanged delivery files / 71,496,968 bytes; all six advertised hashes pass. All 51 inventory files (19,290,536 bytes), five top-level aliases, and 33 nested aliases match. The main archive includes all inventoried files; the smaller browser archive has 33 files and omits 18 inventory items available in the main archive/loose package. No symlinks, unsafe tar paths or differing alias bytes were found.','','# Per-artifact classification','','| ID | Retained PDF | Pages inspected / total | Disposition |','|---|---|---:|---|']
for s in sources:
 md.append(f"| {s['priority_id']} | `{Path(s['file']['path']).name}` | {', '.join(map(str,s['inspected_physical_pages']))} / {s['pages']} | {s['role'].replace('_',' ')}; {s['provenance_class'].replace('_',' ')} |")
md+=['','Full source hashes:']
for s in sources:md.append(f"- {s['priority_id']}: `{s['file']['sha256']}` ({s['file']['size_bytes']:,} bytes).")
md+=['','The addendum metadata identifies Chrome 151 / Skia PDF and a September 11 print time. The staff memo has Aspose metadata dated June 30 / July 6. The minutes have Microsoft Print To PDF metadata dated February 17 and an Administrative Matters filename, while the visible first-page heading says Land Use Hearing. Metadata and filenames do not establish publication, legal dates, certification, or acquisition.','','# Findings','']
for f in F:
 md += [f"## {f['id']} — {f['disposition']}: {f['title']}",'',f['detail'],'','Evidence: '+', '.join('`'+p+'`' for p in f['evidence_paths'])+'.','']
md+=['# Bounded image-supported excerpts','']
for e in excerpts:
 md += [f"**{e['source_priority_id']}, physical page {e['physical_page']}, {e['region']}**",'','> '+e['wording'].replace('\n','\n> '),'',e['qualification'],'']
md+=['# Unresolved work','']+['- '+s for s in data['unresolved_gaps']]
md+=['','Three exact unopened video leads from the July staff memo (not fetched in this audit):','', '- https://www.youtube.com/watch?v=XOBwdU0Q4fU', '- https://www.youtube.com/watch?v=URFMFqDK0zc', '- https://www.youtube.com/watch?v=J0rUVvvjkB8','','The immutable originals remain unchanged. The audit and schema are local handoff artifacts only; no repository, control-plane, raw archive, registry or legal-currentness changes were made. Standalone machine-check results are recorded separately after running `validate_audit.py`.','']
(B/'INTAKE_AUDIT.md').write_text('\n'.join(md))
print('Saved typed audit, schema and Markdown with',len(F),'findings.')
